version: '3.7'

services:
  nginx:
    image: nginx:stable
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/conf.d/includes:/etc/nginx/conf.d/includes
      - ./:/var/www/html
    deploy:
      restart_policy:
        condition: any

  node:
    image: node:14
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    entrypoint: ''
    command: ''
